# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: PowerShell@2
    displayName: Configuration
    inputs:
      targetType: 'inline'
      script: echo $(var)
      
  - task: PowerShell@2
    displayName: Marketplace_Validation
    inputs:
      targetType: 'inline'
      script: |
        # Write your PowerShell commands here.
        
        Write-Host "Hello World Sage 2 | Job 1 | Step 1"
 
